### PR TITLE
Fixes for wasm

### PR DESCRIPTION
**Pull request by juntyr**
Small fixes to get the wasm version to run again. This PR is based on top of #23, so please disregard that extra diff for now, I'll rebase once #23 is merged.

Primarily, this PR adds import checks for the parquet and feather format and pdf export. Some formatting changes occurred since I ran black at the end.

@Aggrathon I'm unsure about the optional dependency changes - these are the packages that cannot be used (or need to be lazily loaded for sklearn) in xiplot right now, but maybe there's a better way to represent that.

Once this PR is merged I have a follow-up for the WASM branch to update it - locally everything seems to be working.

### CODE REVIEW

**Comment by Aggrathon** [comment]
And if optional dependencies are the best solution, then I would group all (non-dev) dependencies into one group.

**Comment by juntyr** [comment]
> I agree that the optional dependencies solution is not optimal. Unfortunately Python doesn't seem to have some kind of "default optional dependencies". The only thing I've been able to find is [conditional dependencies](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies).
> 
> So how about keeping the dependencies required but either:
> 
> a) Filter out the packages in the wasm branch. b) Add conditional specification that always evaluates to true, but can be detected (and filtered) in the wasm branch, e.g. `kaleido ~= 0.2.1; platform_system!='xiplot_wasm'`.

I like that idea and have implemented it :)

**Comment by Aggrathon** [comment]
(Note that I haven't tried a custom conditional dependency myself, so something might complain. But in theory it should work.)

**Review by Aggrathon — APPROVED** [review]
As for the rest of the changes, looks good!

(If you want an unnecessarily future-proof and unnecessarily generic version of the `supports_*_format` function then here is an option: 
```
def supports_format(read_fn: Callable[[BytesIO], pd.DataFrame]) -> bool:
    try:
        read_fn(BytesIO())
    except ImportError:
        return False
    except:
        pass
    return True
```
)

**Comment by Aggrathon** [comment]
Using a [pyodide REPL](https://pyodide.org/en/stable/console.html) I get the following value:
```
>>> import platform
>>> platform.system()
'Emscripten'
```

**Comment by juntyr** [comment]
Superseded by #28

**Pull request closed without merging**
