### PR TITLE
Debug: download embedding columns

### PR DESCRIPTION
**Pull request by TanakaAkihiro**

### CODE REVIEW

**Comment by juntyr** [comment]
Unfortunately this does not yet solve the issue with re-uploading data+plots where a plot depends on xiplot-generated PCA embeddings

**Comment by TanakaAkihiro** [comment]
Hope that this time the fix works :)

@juntyr

**Review by juntyr — APPROVED** [review]
LGTM

**Comment by TanakaAkihiro** [comment]
It seems like cluster data is also stored as strings... I'll merge this one and we could fix it later, if it's fine

**Pull request merged**
